import type { ValidationReport } from './verification';

export interface AgentRunContext {
  runId?: string | null;
  actor?: string;
}

export interface AgentOutcome<T> {
  agentKey: string;
  data: T;
  validation: ValidationReport;
  /** True when the narrative came from the model rather than the rule engine. */
  usedLlm: boolean;
  /** Human-readable notes about how the result was produced. */
  notes: string[];
}

export function outcome<T>(
  agentKey: string,
  data: T,
  validation: ValidationReport,
  usedLlm: boolean,
  notes: string[] = [],
): AgentOutcome<T> {
  return { agentKey, data, validation, usedLlm, notes };
}

export const RULE_ENGINE_NOTE =
  'Generated by the deterministic rule engine (no Anthropic key configured).';
